name: clean_repo_objectbox_example
description: Demonstrates how to use the clean_repo_objectbox plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #for example
  intl: ^0.17.0
  faker: ^2.0.0

  #DB
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  flat_buffers: ^2.0.5
  path_provider: ^2.0.9

  #Architecture
  clean_core: 1.3.4-SNAPSHOT.20221002

  #DB clean
  clean_repo_objectbox:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.8
  objectbox_generator: ^1.4.1

  #flutter pub run dependency_validator
  dependency_validator: ^3.1.2

flutter: