name: clean_repo_objectbox_example
description: Demonstrates how to use the clean_repo_objectbox plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #DB
  objectbox: ^1.7.0
  objectbox_flutter_libs: ^1.7.0
  flat_buffers: ^2.0.5

  #DB clean
  clean_repo_objectbox:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.3.3
  objectbox_generator: ^1.7.0

  #flutter pub run dependency_validator
  dependency_validator: ^3.2.2

flutter: