name: clean_repo_objectbox_example
description: Demonstrates how to use the clean_repo_objectbox plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  faker: ^2.0.0
  objectbox: ^1.2.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.3

  clean_core:
    git:
      url: https://github.com/JesusHdezWaterloo/clean-core-flutter.git

  clean_repo_objectbox:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: