name: clean_repo_objectbox
description: "`clean_repo_objectbox` pretende ser un framework para facilitar y abstraer el uso de la BD ObjectBox en aplicaciones con Clean Arquitecture"
version: 0.1.3-RELEASE.20220206
homepage: https://github.com/JesusHdezWaterloo/clean_repo_objectbox

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.3
  clean_core: ^1.2.3-RELEASE.20220206

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  objectbox_generator: any

flutter:
  plugin:
    platforms:
      android:
        package: com.root101.db.objectbox.clean_repo_objectbox
        pluginClass: CleanRepoObjectboxPlugin
      ios:
        pluginClass: CleanRepoObjectboxPlugin
      web:
        pluginClass: CleanRepoObjectboxWeb
        fileName: clean_repo_objectbox_web.dart