name: clean_repo_objectbox
description: "`clean_repo_objectbox` pretende ser un framework para facilitar y abstraer el uso de la BD ObjectBox en aplicaciones con Clean Arquitecture"
version: 1.2.0-RELEASE.20221217
homepage: https://github.com/JesusHdezWaterloo/clean_repo_objectbox

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #DB
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  flat_buffers: ^2.0.5
  path_provider: ^2.0.9

  #Architecture
  clean_core: 1.4.0-SNAPSHOT.20221217

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.8
  objectbox_generator: ^1.4.1

  #flutter pub run dependency_validator
  dependency_validator: ^3.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.root101.db.objectbox.clean_repo_objectbox
        pluginClass: CleanRepoObjectboxPlugin
      ios:
        pluginClass: CleanRepoObjectboxPlugin